#!/usr/bin/env php
<?php
require __DIR__ . '/credentials.php';
require __DIR__ . '/vendor/autoload.php';

use \Abraham\TwitterOAuth\TwitterOAuth;
$connection = new TwitterOAuth(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);


array_shift($argv);
$tweet = join(' ', $argv);
if (empty($tweet)) {
   $tweet = file_get_contents('php://stdin');
}

$content = $connection->get('account/verify_credentials');
$connection->post('statuses/update', array('status' => $tweet));
$exitCode = $connection->getLastHttpCode() === 200 ? 0 : 1;

exit($exitCode);